#pragma once

#if (SPACE_PLATFORM == SPACE_WIN32)
#include <DirectXMath.h>
#include <DirectXColors.h>
#include <DirectXCollision.h>
#include <DirectXPackedVector.h>

using namespace DirectX;
using namespace DirectX::PackedVector; 
#endif

namespace Space
{

#if (SPACE_PLATFORM == SPACE_WIN32)
	typedef float Float1;
	typedef DirectX::XMFLOAT2 Float2;
	typedef DirectX::XMFLOAT3 Float3;
	typedef DirectX::XMFLOAT4 Float4;
	typedef DirectX::XMFLOAT2A Float2A;
	typedef DirectX::XMFLOAT3A Float3A;
	typedef DirectX::XMFLOAT4A Float4A;
	typedef DirectX::XMUINT2 Uint2;
	typedef DirectX::XMUINT3 Uint3;
	typedef DirectX::XMUINT4 Uint4;
	typedef DirectX::XMINT2 Int2;
	typedef DirectX::XMINT3 Int3;
	typedef DirectX::XMINT4 Int4;
	typedef DirectX::XMFLOAT2 Float2;
	typedef DirectX::XMFLOAT2A Float2A;
	typedef DirectX::XMFLOAT3 Float3;
	typedef DirectX::XMFLOAT3A Float3A;
	typedef DirectX::PackedVector::XMFLOAT3PK Float3PK; //a 3D vector with X and Y components stored as 11 bit floating point number, and Z component stored as a 10 bit floating - point value.
	typedef DirectX::PackedVector::XMFLOAT3SE Float3SE; //a 3D vector of three floating-point components with 9 bit mantissas, each sharing the same 5-bit exponent
	typedef DirectX::XMFLOAT3X3 Float3x3;
	typedef DirectX::XMFLOAT4	Float4;
	typedef DirectX::XMFLOAT4A  Float4A;
	typedef DirectX::XMFLOAT4X3 Float4x3;
	typedef DirectX::XMFLOAT4X3A Float4x3A;
	typedef DirectX::XMFLOAT4X4 Float4x4;
	typedef DirectX::XMFLOAT4X4A Float4x4A;
	typedef DirectX::PackedVector::XMBYTE2 Byte2;
	typedef DirectX::PackedVector::XMBYTE4 Byte4;
	typedef DirectX::PackedVector::XMBYTEN2 ByteN2;
	typedef DirectX::PackedVector::XMBYTEN4 ByteN4;
	typedef DirectX::PackedVector::XMUBYTE2 UByte2; 
	typedef DirectX::PackedVector::XMUBYTE4 UByte4;
	typedef DirectX::PackedVector::XMUBYTEN2 UByteN2;
	typedef DirectX::PackedVector::XMUBYTEN4 UByteN4;
	typedef DirectX::PackedVector::XMUSHORT2 UShort2;
	typedef DirectX::PackedVector::XMUSHORT4 UShort4;
	typedef DirectX::PackedVector::XMUSHORTN2 UShortN2;
	typedef DirectX::PackedVector::XMUSHORTN4 UShortN4;
	typedef DirectX::PackedVector::XMSHORT2 Short2;
	typedef DirectX::PackedVector::XMSHORT4 Short4;
	typedef DirectX::PackedVector::XMSHORTN2 ShortN2; // A 2D vector for storing signed, normalized values as signed 16 - bit integers(type int16_t).
	typedef DirectX::PackedVector::XMSHORTN4 ShortN4;
	typedef DirectX::PackedVector::HALF Half;
	typedef DirectX::PackedVector::XMHALF2 Half2;
	typedef DirectX::PackedVector::XMHALF4 Half4;
	typedef DirectX::PackedVector::XMCOLOR Color;

	typedef DirectX::XMVECTOR Vector;
	typedef DirectX::XMMATRIX Matrix;
	
	const auto Pi = DirectX::XM_PI;
	const auto _2Pi    = DirectX::XM_2PI;
	const auto _1DIVPI = DirectX::XM_1DIVPI;
	const auto PiDiv2  = DirectX::XM_PIDIV2;
	const auto PiDiv4  = DirectX::XM_PIDIV4;

#define ColorSRGBToRGB XMColorSRGBToRGB 
#define ColorRGBToSRGB XMColorRGBToSRGB 
#define ColorAdjustContrast XMColorAdjustContrast 
#define ColorAdjustSaturation XMColorAdjustSaturation 
#define ColorEqual XMColorEqual 
#define ColorGreater XMColorGreater 
#define ColorGreaterOrEqual XMColorGreaterOrEqual 
#define ColorHSLToRGB XMColorHSLToRGB 
#define ColorHSVToRGB XMColorHSVToRGB 
#define ColorIsInfinite XMColorIsInfinite 
#define ColorIsNaN XMColorIsNaN 
#define ColorLess XMColorLess 
#define ColorLessOrEqual XMColorLessOrEqual 
#define ColorModulate XMColorModulate 
#define ColorNegative XMColorNegative 
#define ColorNotEqual XMColorNotEqual 
#define ColorRGBToHSL XMColorRGBToHSL 
#define ColorRGBToHSV XMColorRGBToHSV 
#define ColorRGBToXYZ XMColorRGBToXYZ 
#define ColorRGBToYUV XMColorRGBToYUV 
#define ColorRGBToYUV_HD XMColorRGBToYUV_HD 
#define ColorSRGBToXYZ XMColorSRGBToXYZ 
#define ColorXYZToRGB XMColorXYZToRGB 
#define ColorXYZToSRGB XMColorXYZToSRGB 
#define ColorYUVToRGB XMColorYUVToRGB 
#define ColorYUVToRGB_HD XMColorYUVToRGB_HD 
	
#define ConvertFloatToHalf XMConvertFloatToHalf 
#define ConvertFloatToHalfStream XMConvertFloatToHalfStream 
#define ConvertHalfToFloat XMConvertHalfToFloat 
#define ConvertHalfToFloatStream XMConvertHalfToFloatStream 
#define ConvertToDegrees XMConvertToDegrees 
#define ConvertToRadians XMConvertToRadians 
#define ConvertVectorFloatToInt XMConvertVectorFloatToInt 
#define ConvertVectorFloatToUInt XMConvertVectorFloatToUInt 
#define ConvertVectorIntToFloat XMConvertVectorIntToFloat 
#define ConvertVectorUIntToFloat XMConvertVectorUIntToFloat 

#define MatrixAffineTransformation XMMatrixAffineTransformation 
#define MatrixAffineTransformation2D XMMatrixAffineTransformation2D 
#define MatrixDecompose XMMatrixDecompose 
#define MatrixDeterminant XMMatrixDeterminant 
#define MatrixIdentity XMMatrixIdentity 
#define MatrixInverse XMMatrixInverse 
#define MatrixIsIdentity XMMatrixIsIdentity 
#define MatrixIsInfinite XMMatrixIsInfinite 
#define MatrixIsNaN XMMatrixIsNaN 
#define MatrixLookAtLH XMMatrixLookAtLH 
#define MatrixLookAtRH XMMatrixLookAtRH 
#define MatrixLookToLH XMMatrixLookToLH 
#define MatrixLookToRH XMMatrixLookToRH 
#define MatrixMultiply XMMatrixMultiply 
#define MatrixMultiplyTranspose XMMatrixMultiplyTranspose 
#define MatrixOrthographicLH XMMatrixOrthographicLH 
#define MatrixOrthographicOffCenterLH XMMatrixOrthographicOffCenterLH 
#define MatrixOrthographicOffCenterRH XMMatrixOrthographicOffCenterRH 
#define MatrixOrthographicRH XMMatrixOrthographicRH 
#define MatrixPerspectiveFovLH XMMatrixPerspectiveFovLH 
#define MatrixPerspectiveFovRH XMMatrixPerspectiveFovRH 
#define MatrixPerspectiveLH XMMatrixPerspectiveLH 
#define MatrixPerspectiveOffCenterLH XMMatrixPerspectiveOffCenterLH 
#define MatrixPerspectiveOffCenterRH XMMatrixPerspectiveOffCenterRH 
#define MatrixPerspectiveRH XMMatrixPerspectiveRH 
#define MatrixReflect XMMatrixReflect 
#define MatrixRotationAxis XMMatrixRotationAxis 
#define MatrixRotationNormal XMMatrixRotationNormal 
#define MatrixRotationQuaternion XMMatrixRotationQuaternion 
#define MatrixRotationRollPitchYaw XMMatrixRotationRollPitchYaw 
#define MatrixRotationRollPitchYawFromVector XMMatrixRotationRollPitchYawFromVector 
#define MatrixRotationX XMMatrixRotationX 
#define MatrixRotationY XMMatrixRotationY 
#define MatrixRotationZ XMMatrixRotationZ 
#define MatrixScaling XMMatrixScaling 
#define MatrixScalingFromVector XMMatrixScalingFromVector 
#define MatrixSet XMMatrixSet 
#define MatrixShadow XMMatrixShadow 
#define MatrixTransformation XMMatrixTransformation 
#define MatrixTransformation2D XMMatrixTransformation2D 
#define MatrixTranslation XMMatrixTranslation 
#define MatrixTranslationFromVector XMMatrixTranslationFromVector 
#define MatrixTranspose XMMatrixTranspose 

#define PlaneDot XMPlaneDot 
#define PlaneDotCoord XMPlaneDotCoord 
#define PlaneDotNormal XMPlaneDotNormal 
#define PlaneEqual XMPlaneEqual 
#define PlaneFromPointNormal XMPlaneFromPointNormal 
#define PlaneFromPoints XMPlaneFromPoints 
#define PlaneIntersectLine XMPlaneIntersectLine 
#define PlaneIntersectPlane XMPlaneIntersectPlane 
#define PlaneIsInfinite XMPlaneIsInfinite 
#define PlaneIsNaN XMPlaneIsNaN 
#define PlaneNearEqual XMPlaneNearEqual 
#define PlaneNormalize XMPlaneNormalize 
#define PlaneNormalizeEst XMPlaneNormalizeEst 
#define PlaneNotEqual XMPlaneNotEqual 
#define PlaneTransform XMPlaneTransform 
#define PlaneTransformStream XMPlaneTransformStream 

#define QuaternionBaryCentric XMQuaternionBaryCentric 
#define QuaternionBaryCentricV XMQuaternionBaryCentricV 
#define QuaternionConjugate XMQuaternionConjugate 
#define QuaternionDot XMQuaternionDot 
#define QuaternionEqual XMQuaternionEqual 
#define QuaternionExp XMQuaternionExp 
#define QuaternionIdentity XMQuaternionIdentity 
#define QuaternionInverse XMQuaternionInverse 
#define QuaternionIsIdentity XMQuaternionIsIdentity 
#define QuaternionIsInfinite XMQuaternionIsInfinite 
#define QuaternionIsNaN XMQuaternionIsNaN 
#define QuaternionLength XMQuaternionLength 
#define QuaternionLengthSq XMQuaternionLengthSq 
#define QuaternionLn XMQuaternionLn 
#define QuaternionMultiply XMQuaternionMultiply 
#define QuaternionNormalize XMQuaternionNormalize 
#define QuaternionNormalizeEst XMQuaternionNormalizeEst 
#define QuaternionNotEqual XMQuaternionNotEqual 
#define QuaternionReciprocalLength XMQuaternionReciprocalLength 
#define QuaternionRotationAxis XMQuaternionRotationAxis 
#define QuaternionRotationMatrix XMQuaternionRotationMatrix 
#define QuaternionRotationNormal XMQuaternionRotationNormal 
#define QuaternionRotationRollPitchYaw XMQuaternionRotationRollPitchYaw 
#define QuaternionRotationRollPitchYawFromVector XMQuaternionRotationRollPitchYawFromVector 
#define QuaternionSlerp XMQuaternionSlerp 
#define QuaternionSlerpV XMQuaternionSlerpV 
#define QuaternionSquad XMQuaternionSquad 
#define QuaternionSquadSetup XMQuaternionSquadSetup 
#define QuaternionSquadV XMQuaternionSquadV 
#define QuaternionToAxisAngle XMQuaternionToAxisAngle 

#define ScalarACos XMScalarACos 
#define ScalarACosEst XMScalarACosEst 
#define ScalarASin XMScalarASin 
#define ScalarASinEst XMScalarASinEst 
#define ScalarCos XMScalarCos 
#define ScalarCosEst XMScalarCosEst 
#define ScalarModAngle XMScalarModAngle 
#define ScalarNearEqual XMScalarNearEqual 
#define ScalarSin XMScalarSin 
#define ScalarSinCos XMScalarSinCos 
#define ScalarSinCosEst XMScalarSinCosEst 
#define ScalarSinEst XMScalarSinEst 

#define VectorAbs XMVectorAbs 
#define VectorAdd XMVectorAdd 
#define VectorAddAngles XMVectorAddAngles 
#define VectorCeiling XMVectorCeiling 
#define VectorClamp XMVectorClamp 
#define VectorDivide XMVectorDivide 
#define VectorFloor XMVectorFloor 
#define VectorIsInfinite XMVectorIsInfinite 
#define VectorIsNaN XMVectorIsNaN 
#define VectorMax XMVectorMax 
#define VectorMin XMVectorMin 
#define VectorMod XMVectorMod 
#define VectorModAngles XMVectorModAngles 
#define VectorMultiply XMVectorMultiply 
#define VectorMultiplyAdd XMVectorMultiplyAdd 
#define VectorNegate XMVectorNegate 
#define VectorNegativeMultiplySubtract XMVectorNegativeMultiplySubtract 
#define VectorPow XMVectorPow 
#define VectorReciprocal XMVectorReciprocal 
#define VectorReciprocalEst XMVectorReciprocalEst 
#define VectorReciprocalSqrt XMVectorReciprocalSqrt 
#define VectorReciprocalSqrtEst XMVectorReciprocalSqrtEst 
#define VectorRound XMVectorRound 
#define VectorSaturate XMVectorSaturate 
#define VectorScale XMVectorScale 
#define VectorSqrt XMVectorSqrt 
#define VectorSqrtEst XMVectorSqrtEst 
#define VectorSubtract XMVectorSubtract 
#define VectorSubtractAngles XMVectorSubtractAngles 
#define VectorTruncate XMVectorTruncate 

#define VectorAndCInt XMVectorAndCInt 
#define VectorAndInt XMVectorAndInt 
#define VectorNorInt XMVectorNorInt 
#define VectorNotEqual XMVectorNotEqual 
#define VectorNotEqualInt XMVectorNotEqualInt 
#define VectorOrInt XMVectorOrInt 
#define VectorXorInt XMVectorXorInt 

#define VectorEqual XMVectorEqual 
#define VectorEqualInt XMVectorEqualInt 
#define VectorEqualIntR XMVectorEqualIntR 
#define VectorEqualR XMVectorEqualR 
#define VectorGreater XMVectorGreater 
#define VectorGreaterOrEqual XMVectorGreaterOrEqual 
#define VectorGreaterOrEqualR XMVectorGreaterOrEqualR 
#define VectorGreaterR XMVectorGreaterR 
#define VectorLess XMVectorLess 
#define VectorLessOrEqual XMVectorLessOrEqual 
#define VectorNearEqual XMVectorNearEqual 

#define VectorInsert XMVectorInsert 
#define VectorMergeXY XMVectorMergeXY 
#define VectorMergeZW XMVectorMergeZW 
#define VectorPermute XMVectorPermute 
#define VectorRotateLeft XMVectorRotateLeft 
#define VectorRotateRight XMVectorRotateRight 
#define VectorSelect XMVectorSelect 
#define VectorSelectControl XMVectorSelectControl 
#define VectorShiftLeft XMVectorShiftLeft 
#define VectorSplatW XMVectorSplatW 
#define VectorSplatX XMVectorSplatX 
#define VectorSplatY XMVectorSplatY 
#define VectorSplatZ XMVectorSplatZ 
#define VectorSwizzle XMVectorSwizzle 

#define VectorBaryCentric XMVectorBaryCentric 
#define VectorBaryCentricV XMVectorBaryCentricV 
#define VectorCatmullRom XMVectorCatmullRom 
#define VectorCatmullRomV XMVectorCatmullRomV 
#define VectorHermite XMVectorHermite 
#define VectorHermiteV XMVectorHermiteV 
#define VectorInBounds XMVectorInBounds 
#define VectorInBoundsR XMVectorInBoundsR 
#define VectorLerp XMVectorLerp 
#define VectorLerpV XMVectorLerpV 

#define VectorFalseInt XMVectorFalseInt 
#define VectorReplicate XMVectorReplicate 
#define VectorReplicateInt XMVectorReplicateInt 
#define VectorReplicateIntPtr XMVectorReplicateIntPtr 
#define VectorReplicatePtr XMVectorReplicatePtr 
#define VectorSet XMVectorSet 
#define VectorSetBinaryConstant XMVectorSetBinaryConstant 
#define VectorSetInt XMVectorSetInt 
#define VectorSplatConstant XMVectorSplatConstant 
#define VectorSplatConstantInt XMVectorSplatConstantInt 
#define VectorSplatEpsilon XMVectorSplatEpsilon 
#define VectorSplatInfinity XMVectorSplatInfinity 
#define VectorSplatOne XMVectorSplatOne 
#define VectorSplatQNaN XMVectorSplatQNaN 
#define VectorSplatSignMask XMVectorSplatSignMask 
#define VectorTrueInt XMVectorTrueInt 
#define VectorZero XMVectorZero 

#define VectorACos XMVectorACos 
#define VectorACosEst XMVectorACosEst 
#define VectorASin XMVectorASin 
#define VectorASinEst XMVectorASinEst 
#define VectorATan XMVectorATan 
#define VectorATan2 XMVectorATan2 
#define VectorATan2Est XMVectorATan2Est 
#define VectorATanEst XMVectorATanEst 
#define VectorCos XMVectorCos 
#define VectorCosEst XMVectorCosEst 
#define VectorCosH XMVectorCosH 
#define VectorExp XMVectorExp 
#define VectorExp2 XMVectorExp2 
#define VectorExpE XMVectorExpE 
#define VectorLog XMVectorLog 
#define VectorLog2 XMVectorLog2 
#define VectorLogE XMVectorLogE 
#define VectorSin XMVectorSin 
#define VectorSinCos XMVectorSinCos 
#define VectorSinCosEst XMVectorSinCosEst 
#define VectorSinEst XMVectorSinEst 
#define VectorSinH XMVectorSinH 
#define VectorTan XMVectorTan 
#define VectorTanEst XMVectorTanEst 
#define VectorTanH XMVectorTanH 

#define Vector2Equal XMVector2Equal 
#define Vector2EqualInt XMVector2EqualInt 
#define Vector2EqualIntR XMVector2EqualIntR 
#define Vector2EqualR XMVector2EqualR 
#define Vector2Greater XMVector2Greater 
#define Vector2GreaterOrEqual XMVector2GreaterOrEqual 
#define Vector2GreaterOrEqualR XMVector2GreaterOrEqualR 
#define Vector2GreaterR XMVector2GreaterR 
#define Vector2IsInfinite XMVector2IsInfinite 
#define Vector2IsNaN XMVector2IsNaN 
#define Vector2Less XMVector2Less 
#define Vector2LessOrEqual XMVector2LessOrEqual 
#define Vector2NearEqual XMVector2NearEqual 
#define Vector2NotEqual XMVector2NotEqual 
#define Vector2NotEqualInt XMVector2NotEqualInt 
#define Vector2AngleBetweenNormals XMVector2AngleBetweenNormals 
#define Vector2AngleBetweenNormalsEst XMVector2AngleBetweenNormalsEst 
#define Vector2AngleBetweenVectors XMVector2AngleBetweenVectors 
#define Vector2ClampLength XMVector2ClampLength 
#define Vector2ClampLengthV XMVector2ClampLengthV 
#define Vector2Cross XMVector2Cross 
#define Vector2Dot XMVector2Dot 
#define Vector2InBounds XMVector2InBounds 
#define Vector2IntersectLine XMVector2IntersectLine 
#define Vector2Length XMVector2Length 
#define Vector2LengthEst XMVector2LengthEst 
#define Vector2LengthSq XMVector2LengthSq 
#define Vector2LinePointDistance XMVector2LinePointDistance 
#define Vector2Normalize XMVector2Normalize 
#define Vector2NormalizeEst XMVector2NormalizeEst 
#define Vector2Orthogonal XMVector2Orthogonal 
#define Vector2ReciprocalLength XMVector2ReciprocalLength 
#define Vector2ReciprocalLengthEst XMVector2ReciprocalLengthEst 
#define Vector2Reflect XMVector2Reflect 
#define Vector2Refract XMVector2Refract 
#define Vector2RefractV XMVector2RefractV 

#define Vector2Transform XMVector2Transform 
#define Vector2TransformCoord XMVector2TransformCoord 
#define Vector2TransformCoordStream XMVector2TransformCoordStream 
#define Vector2TransformNormal XMVector2TransformNormal 
#define Vector2TransformNormalStream XMVector2TransformNormalStream 
#define Vector2TransformStream XMVector2TransformStream 
#define Vector3Equal XMVector3Equal 
#define Vector3EqualInt XMVector3EqualInt 
#define Vector3EqualIntR XMVector3EqualIntR 
#define Vector3EqualR XMVector3EqualR 
#define Vector3Greater XMVector3Greater 
#define Vector3GreaterOrEqual XMVector3GreaterOrEqual 
#define Vector3GreaterOrEqualR XMVector3GreaterOrEqualR 
#define Vector3GreaterR XMVector3GreaterR 
#define Vector3IsInfinite XMVector3IsInfinite 
#define Vector3IsNaN XMVector3IsNaN 
#define Vector3Less XMVector3Less 
#define Vector3LessOrEqual XMVector3LessOrEqual 
#define Vector3NearEqual XMVector3NearEqual 
#define Vector3NotEqual XMVector3NotEqual 
#define Vector3NotEqualInt XMVector3NotEqualInt 

#define Vector3AngleBetweenNormals XMVector3AngleBetweenNormals 
#define Vector3AngleBetweenNormalsEst XMVector3AngleBetweenNormalsEst 
#define Vector3AngleBetweenVectors XMVector3AngleBetweenVectors 
#define Vector3ClampLength XMVector3ClampLength 
#define Vector3ClampLengthV XMVector3ClampLengthV 
#define Vector3ComponentsFromNormal XMVector3ComponentsFromNormal 
#define Vector3Cross XMVector3Cross 
#define Vector3Dot XMVector3Dot 
#define Vector3InBounds XMVector3InBounds 
#define Vector3Length XMVector3Length 
#define Vector3LengthEst XMVector3LengthEst 
#define Vector3LengthSq XMVector3LengthSq 
#define Vector3LinePointDistance XMVector3LinePointDistance 
#define Vector3Normalize XMVector3Normalize 
#define Vector3NormalizeEst XMVector3NormalizeEst 
#define Vector3Orthogonal XMVector3Orthogonal 
#define Vector3ReciprocalLength XMVector3ReciprocalLength 
#define Vector3ReciprocalLengthEst XMVector3ReciprocalLengthEst 
#define Vector3Reflect XMVector3Reflect 
#define Vector3Refract XMVector3Refract 
#define Vector3RefractV XMVector3RefractV 

#define Vector3InverseRotate XMVector3InverseRotate 
#define Vector3Project XMVector3Project 
#define Vector3ProjectStream XMVector3ProjectStream 
#define Vector3Rotate XMVector3Rotate 
#define Vector3Transform XMVector3Transform 
#define Vector3TransformCoord XMVector3TransformCoord 
#define Vector3TransformCoordStream XMVector3TransformCoordStream 
#define Vector3TransformNormal XMVector3TransformNormal 
#define Vector3TransformNormalStream XMVector3TransformNormalStream 
#define Vector3TransformStream XMVector3TransformStream 
#define Vector3Unproject XMVector3Unproject 
#define Vector3UnprojectStream XMVector3UnprojectStream 

#define Vector4Equal XMVector4Equal 
#define Vector4EqualInt XMVector4EqualInt 
#define Vector4EqualIntR XMVector4EqualIntR 
#define Vector4EqualR XMVector4EqualR 
#define Vector4Greater XMVector4Greater 
#define Vector4GreaterOrEqual XMVector4GreaterOrEqual 
#define Vector4GreaterOrEqualR XMVector4GreaterOrEqualR 
#define Vector4GreaterR XMVector4GreaterR 
#define Vector4IsInfinite XMVector4IsInfinite 
#define Vector4IsNaN XMVector4IsNaN 
#define Vector4Less XMVector4Less 
#define Vector4LessOrEqual XMVector4LessOrEqual 
#define Vector4NearEqual XMVector4NearEqual 
#define Vector4NotEqual XMVector4NotEqual 
#define Vector4NotEqualInt XMVector4NotEqualInt 
#define Vector4AngleBetweenNormals XMVector4AngleBetweenNormals 
#define Vector4AngleBetweenNormalsEst XMVector4AngleBetweenNormalsEst 
#define Vector4AngleBetweenVectors XMVector4AngleBetweenVectors 
#define Vector4ClampLength XMVector4ClampLength 
#define Vector4ClampLengthV XMVector4ClampLengthV 
#define Vector4Cross XMVector4Cross 
#define Vector4Dot XMVector4Dot 
#define Vector4InBounds XMVector4InBounds 
#define Vector4Length XMVector4Length 
#define Vector4LengthEst XMVector4LengthEst 
#define Vector4LengthSq XMVector4LengthSq 
#define Vector4Normalize XMVector4Normalize 
#define Vector4NormalizeEst XMVector4NormalizeEst 
#define Vector4Orthogonal XMVector4Orthogonal 
#define Vector4ReciprocalLength XMVector4ReciprocalLength 
#define Vector4ReciprocalLengthEst XMVector4ReciprocalLengthEst 
#define Vector4Reflect XMVector4Reflect 
#define Vector4Refract XMVector4Refract 
#define Vector4RefractV XMVector4RefractV 

#define Vector4Transform XMVector4Transform 
#define Vector4TransformStream XMVector4TransformStream 
#define ComparisonAllFalse XMComparisonAllFalse 
#define ComparisonAllInBounds XMComparisonAllInBounds 
#define ComparisonAllTrue XMComparisonAllTrue 
#define ComparisonAnyFalse XMComparisonAnyFalse 
#define ComparisonAnyOutOfBounds XMComparisonAnyOutOfBounds 
#define ComparisonAnyTrue XMComparisonAnyTrue 
#define ComparisonMixed XMComparisonMixed 
#define FresnelTerm XMFresnelTerm 
#define VerifyCPUSupport XMVerifyCPUSupport 

#define VectorGetByIndex XMVectorGetByIndex 
#define VectorGetByIndexPtr XMVectorGetByIndexPtr 
#define VectorGetIntByIndex XMVectorGetIntByIndex 
#define VectorGetIntByIndexPtr XMVectorGetIntByIndexPtr 
#define VectorGetIntW XMVectorGetIntW 
#define VectorGetIntWPtr XMVectorGetIntWPtr 
#define VectorGetIntX XMVectorGetIntX 
#define VectorGetIntXPtr XMVectorGetIntXPtr 
#define VectorGetIntY XMVectorGetIntY 
#define VectorGetIntYPtr XMVectorGetIntYPtr 
#define VectorGetIntZ XMVectorGetIntZ 
#define VectorGetIntZPtr XMVectorGetIntZPtr 
#define VectorGetW XMVectorGetW 
#define VectorGetWPtr XMVectorGetWPtr 
#define VectorGetX XMVectorGetX 
#define VectorGetXPtr XMVectorGetXPtr 
#define VectorGetY XMVectorGetY 
#define VectorGetYPtr XMVectorGetYPtr 
#define VectorGetZ XMVectorGetZ 
#define VectorGetZPtr XMVectorGetZPtr 
#define VectorSetByIndex XMVectorSetByIndex 
#define VectorSetByIndexPtr XMVectorSetByIndexPtr 
#define VectorSetIntByIndex XMVectorSetIntByIndex 
#define VectorSetIntByIndexPtr XMVectorSetIntByIndexPtr 
#define VectorSetIntW XMVectorSetIntW 
#define VectorSetIntWPtr XMVectorSetIntWPtr 
#define VectorSetIntX XMVectorSetIntX 
#define VectorSetIntXPtr XMVectorSetIntXPtr 
#define VectorSetIntY XMVectorSetIntY 
#define VectorSetIntYPtr XMVectorSetIntYPtr 
#define VectorSetIntZ XMVectorSetIntZ 
#define VectorSetIntZPtr XMVectorSetIntZPtr 
#define VectorSetW XMVectorSetW 
#define VectorSetWPtr XMVectorSetWPtr 
#define VectorSetX XMVectorSetX 
#define VectorSetXPtr XMVectorSetXPtr 
#define VectorSetY XMVectorSetY 
#define VectorSetYPtr XMVectorSetYPtr 
#define VectorSetZ XMVectorSetZ 
#define VectorSetZPtr XMVectorSetZPtr 

#define LoadByte2 XMLoadByte2 
#define LoadByte4 XMLoadByte4 
#define LoadByteN2 XMLoadByteN2 
#define LoadByteN4 XMLoadByteN4 
#define LoadColor XMLoadColor 
#define LoadDec4 XMLoadDec4 
#define LoadDecN4 XMLoadDecN4 
#define LoadFloat XMLoadFloat 
#define LoadFloat2 XMLoadFloat2 
#define LoadFloat2A XMLoadFloat2A 
#define LoadFloat3 XMLoadFloat3 
#define LoadFloat3A XMLoadFloat3A 
#define LoadFloat3PK XMLoadFloat3PK 
#define LoadFloat3SE XMLoadFloat3SE 
#define LoadFloat3x3 XMLoadFloat3x3 
#define LoadFloat4 XMLoadFloat4 
#define LoadFloat4A XMLoadFloat4A 
#define LoadFloat4x3 XMLoadFloat4x3 
#define LoadFloat4x3A XMLoadFloat4x3A 
#define LoadFloat4x4 XMLoadFloat4x4 
#define LoadFloat4x4A XMLoadFloat4x4A 
#define LoadHalf2 XMLoadHalf2 
#define LoadHalf4 XMLoadHalf4 
#define LoadInt XMLoadInt 
#define LoadInt2 XMLoadInt2 
#define LoadInt2A XMLoadInt2A 
#define LoadInt3 XMLoadInt3 
#define LoadInt3A XMLoadInt3A 
#define LoadInt4 XMLoadInt4 
#define LoadInt4A XMLoadInt4A 
#define LoadShort2 XMLoadShort2 
#define LoadShort4 XMLoadShort4 
#define LoadShortN2 XMLoadShortN2 
#define LoadShortN4 XMLoadShortN4 
#define LoadSInt2 XMLoadSInt2 
#define LoadSInt3 XMLoadSInt3 
#define LoadSInt4 XMLoadSInt4 
#define LoadU555 XMLoadU555 
#define LoadU565 XMLoadU565 
#define LoadUByte2 XMLoadUByte2 
#define LoadUByte4 XMLoadUByte4 
#define LoadUByteN2 XMLoadUByteN2 
#define LoadUByteN4 XMLoadUByteN4 
#define LoadUDec4 XMLoadUDec4 
#define LoadUDecN4 XMLoadUDecN4 
#define LoadUDecN4_XR XMLoadUDecN4_XR 
#define LoadUInt2 XMLoadUInt2 
#define LoadUInt3 XMLoadUInt3 
#define LoadUInt4 XMLoadUInt4 
#define LoadUNibble4 XMLoadUNibble4 
#define LoadUShort2 XMLoadUShort2 
#define LoadUShort4 XMLoadUShort4 
#define LoadUShortN2 XMLoadUShortN2 
#define LoadUShortN4 XMLoadUShortN4 
#define LoadXDec4 XMLoadXDec4 
#define LoadXDecN4 XMLoadXDecN4 

#define StoreByte2 XMStoreByte2 
#define StoreByte4 XMStoreByte4 
#define StoreByteN2 XMStoreByteN2 
#define StoreByteN4 XMStoreByteN4 
#define StoreColor XMStoreColor 
#define StoreDec4 XMStoreDec4 
#define StoreDecN4 XMStoreDecN4 
#define StoreFloat XMStoreFloat 
#define StoreFloat2 XMStoreFloat2 
#define StoreFloat2A XMStoreFloat2A 
#define StoreFloat3 XMStoreFloat3 
#define StoreFloat3A XMStoreFloat3A 
#define StoreFloat3PK XMStoreFloat3PK 
#define StoreFloat3SE XMStoreFloat3SE 
#define StoreFloat3x3 XMStoreFloat3x3 
#define StoreFloat4 XMStoreFloat4 
#define StoreFloat4A XMStoreFloat4A 
#define StoreFloat4x3 XMStoreFloat4x3 
#define StoreFloat4x3A XMStoreFloat4x3A 
#define StoreFloat4x4 XMStoreFloat4x4 
#define StoreFloat4x4A XMStoreFloat4x4A 
#define StoreHalf2 XMStoreHalf2 
#define StoreHalf4 XMStoreHalf4 
#define StoreInt XMStoreInt 
#define StoreInt2 XMStoreInt2 
#define StoreInt2A XMStoreInt2A 
#define StoreInt3 XMStoreInt3 
#define StoreInt3A XMStoreInt3A 
#define StoreInt4 XMStoreInt4 
#define StoreInt4A XMStoreInt4A 
#define StoreShort2 XMStoreShort2 
#define StoreShort4 XMStoreShort4 
#define StoreShortN2 XMStoreShortN2 
#define StoreShortN4 XMStoreShortN4 
#define StoreSInt2 XMStoreSInt2 
#define StoreSInt3 XMStoreSInt3 
#define StoreSInt4 XMStoreSInt4 
#define StoreU555 XMStoreU555 
#define StoreU565 XMStoreU565 
#define StoreUByte2 XMStoreUByte2 
#define StoreUByte4 XMStoreUByte4 
#define StoreUByteN2 XMStoreUByteN2 
#define StoreUByteN4 XMStoreUByteN4 
#define StoreUDec4 XMStoreUDec4 
#define StoreUDecN4 XMStoreUDecN4 
#define StoreUDecN4_XR XMStoreUDecN4_XR 
#define StoreUInt2 XMStoreUInt2 
#define StoreUInt3 XMStoreUInt3 
#define StoreUInt4 XMStoreUInt4 
#define StoreUNibble4 XMStoreUNibble4 
#define StoreUShort2 XMStoreUShort2 
#define StoreUShort4 XMStoreUShort4 
#define StoreUShortN2 XMStoreUShortN2 
#define StoreUShortN4 XMStoreUShortN4 
#define StoreXDec4 XMStoreXDec4 
#define StoreXDecN4 XMStoreXDecN4 

#endif

}